[font]
normal = { family = "JetBrainsMono NFM", style = "Regular" }
bold = { family = "JetBrainsMono NFM", style = "Bold" }
italic = { family = "JetBrainsMono NFM", style = "Italic" }
size = 14.0

[terminal.shell]
program = "/opt/homebrew/bin/fish"
