require('keymaps')
require('plugins.lazy')
require('plugins.misc')
require('plugins.lualine')
require('options')
require('misc')
require('plugins.dap')
require('plugins.gitsigns')
require('plugins.tele')
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.trouble')
require('plugins.obsidian')
require('plugins.zenmode')
require('plugins.neogit')
require('plugins.codesnap')
require('plugins.harpoon')
require('plugins.ai')
require('plugins.oil')
require('plugins.whichkey')
require('plugins.conform')
require('plugins.flash')
require('plugins.session')
require('plugins.dashboard')

-- vim: ts=8 sts=2 sw=2 et
