default-sample-format = s16le
default-sample-rate = 44100
alternate-sample-rate = 48000
default-sample-channels = 2
resample-method = speex-float-3
avoid-resampling = yes
default-fragments = 8
default-fragment-size-msec = 25
flat-volumes = no
